### PR TITLE
Handle cases where a passed in array might be empty

### PR DESCRIPTION
**Pull request by keyurdg**
PHP 7.3 has an optimization for empty arrays, it's a const called `zend_empty_array`. Calling `zend_hash_internal_pointer_reset` on it leads to an access violation SEGV.

Also fix const warning w/r/t smart_string.

### CODE REVIEW

**Comment by keyurdg** [comment]
@nikic wondering if we could/should make `zend_hash_internal_pointer_reset` and others like it that mutate the passed in HT check for `zend_empty_array` to prevent issues like this one in other extensions.

**Comment by nikic** [comment]
@keyurdg If you run into a situation where these APIs are working on a zend_empty_array, the code is already subtly buggy because it may corrupt the array pointer of a shared array. zend_empty_array only makes that a segfault rather than silent corruption. Using the `_ex` APIs here is the right way, because it does not change potentially shared array state. Even better would be to use ZEND_HASH_FOREACH, something like

```
ZEND_HASH_FOREACH_KEY_VAL(oauth_args, cur_key, num_key, curval) {
    // ...
} ZEND_HASH_FOREACH_END();
```

in this case. These APIs are more ergonomic, safer and faster than using the internal array pointer.

**Comment by keyurdg** [comment]
@nikic thanks for looking! What do you think of adding pointer checks like so to those API methods?
``` 
if (ht == &zend_empty_array) {
    return;
}
```

**Comment by rlerdorf** [comment]
It probably does make sense to switch to `ZEND_HASH_FOREACH_KEY_VAL` but I will merge this for now.

**Comment by rlerdorf** [comment]
Ah, there is still a segfault in `tests/rsa.phpt`
I will dig into that tomorrow

**Pull request merged**
